name: libft CI/CD Pipeline

on: # triggerss
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  watch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  test-libft:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
     
      - name: setup pyhton for norminette
        uses: actions/setup-python@v5
        with:
         python-version: '3.x'
      
      - name: install norminette
        run: pip install norminette
        
      - name: Compile Libft Library
        run: make

      - name: run test
        run: |
          cc test.c libft.a -o test_runner
          ./test_runner
      
      - name: run norminette test
        run: norminette ft_*.c libft.h
  deploy-libft:
    needs: test-libft
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: build libft
        run: make
      - name: creat github release
        uses: softprops/action-gh-release@v3
        with: 
          tag_name: v1.0.${{ github.run_number }}
          files: |
            libft.a 
            libft.h